### ISSUE TITLE
RESP API: Deleting the attachment for a given release throws Could not load user from authentication

### ISSUE THREAD

**Issue by dineshr93** [eclipse-sw360/sw360#1200]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

I am testing the deletion of attachment for the release using the api doc 
http://sw360_url/resource/docs/api-guide.html#resources-release-attachment-delete

When I try it threw the below error 

### Versions

* Last commit id on master: Version: 13.2.0 | Branch: UNKNOWN (2c776f9)
* Operating System (lsb_release -a): 18.04.5 LTS

#### API request response logs
request & response in api testing tool

![image](https://user-images.githubusercontent.com/4498415/117451784-40d06180-af43-11eb-95d8-19f66f82a9e3.png)

```
{
  "timestamp": "2021-05-07T12:42:07.694979Z",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Could not load user from authentication."
}
```

But other get requests succeeds 

![image](https://user-images.githubusercontent.com/4498415/117452358-f56a8300-af43-11eb-93e9-6cde7eadf6f9.png)

#### Tomcat logs
```

2021-05-07 12:42:07 ERROR SW360Assert:141 - Invalid empty email UserHandler.java: 59
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:128) [datahandler-13.2.0.jar:?]
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:84) [datahandler-13.2.0.jar:?]
        at org.eclipse.sw360.users.UserHandler.getByEmail(UserHandler.java:50) [src-users-13.2.0.jar:?]
        at org.eclipse.sw360.users.UserHandler.getByEmailOrExternalId(UserHandler.java:59) [src-users-13.2.0.jar:?]
        at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$getByEmailOrExternalId.getResult(UserService.java:834) [datahandler-13.2.0.jar:?]
        at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$getByEmailOrExternalId.getResult(UserService.java:814) [datahandler-13.2.0.jar:?]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [datahandler-13.2.0.jar:?]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [datahandler-13.2.0.jar:?]
        at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [datahandler-13.2.0.jar:?]
        at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-13.2.0.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-05-07 12:42:07 ERROR ProcessFunction:47 - Internal error processing getByEmailOrExternalId
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:142) ~[datahandler-13.2.0.jar:?]
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:129) ~[datahandler-13.2.0.jar:?]
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:84) ~[datahandler-13.2.0.jar:?]
        at org.eclipse.sw360.users.UserHandler.getByEmail(UserHandler.java:50) ~[src-users-13.2.0.jar:?]
        at org.eclipse.sw360.users.UserHandler.getByEmailOrExternalId(UserHandler.java:59) ~[src-users-13.2.0.jar:?]
        at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$getByEmailOrExternalId.getResult(UserService.java:834) ~[datahandler-13.2.0.jar:?]
        at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$getByEmailOrExternalId.getResult(UserService.java:814) ~[datahandler-13.2.0.jar:?]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [datahandler-13.2.0.jar:?]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [datahandler-13.2.0.jar:?]
        at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [datahandler-13.2.0.jar:?]
        at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-13.2.0.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by dineshr93** [comment]
can any one help on this issue?

**Comment by dineshr93** [comment]
Also as per documentation and https://github.com/eclipse/sw360/pull/899
  I removed the release from being used by any project & tested again. It threw same error as mentioned above.

![image](https://user-images.githubusercontent.com/4498415/121823086-3e2ffd00-cca3-11eb-889c-d0cc647c4a2a.png)

**Comment by dineshr93** [comment]
Have any one by chance checked this attachment deletion via the api ?

**Comment by mcjaeger** [comment]
no I am sorry, but will try it soon.

**Comment by ravi110336** [comment]
Hi @dineshr93 , as per the logs seems the issue is with the UserId which is passed as null, and because of that our user Service is unable to authenticate before even calling the delete attachment api. Could you please try with the current master branch.

I tested the delete attachment for a release in my local with the current master branch and it works fine.

**Comment by dineshr93** [comment]
@ravi110336   I installed the current master e9856a4 when i tried to delete the attachment via rest api i got the below error

```
2021-07-29 15:21:57 ERROR SW360Assert:141 - Invalid empty email UserHandler.java: 67
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:128) [datahandler-13.4.0.jar:?]
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:84) [datahandler-13.4.0.jar:?]
        at org.eclipse.sw360.users.UserHandler.getByEmail(UserHandler.java:58) [src-users-13.4.0.jar:?]
        at org.eclipse.sw360.users.UserHandler.getByEmailOrExternalId(UserHandler.java:67) [src-users-13.4.0.jar:?]
        at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$getByEmailOrExternalId.getResult(UserService.java:834) [datahandler-13.4.0.jar:?]
        at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$getByEmailOrExternalId.getResult(UserService.java:814) [datahandler-13.4.0.jar:?]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [datahandler-13.4.0.jar:?]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [datahandler-13.4.0.jar:?]
        at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [datahandler-13.4.0.jar:?]
        at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-13.4.0.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-07-29 15:21:57 ERROR ProcessFunction:47 - Internal error processing getByEmailOrExternalId
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:142) ~[datahandler-13.4.0.jar:?]
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:129) ~[datahandler-13.4.0.jar:?]
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:84) ~[datahandler-13.4.0.jar:?]
        at org.eclipse.sw360.users.UserHandler.getByEmail(UserHandler.java:58) ~[src-users-13.4.0.jar:?]
        at org.eclipse.sw360.users.UserHandler.getByEmailOrExternalId(UserHandler.java:67) ~[src-users-13.4.0.jar:?]
        at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$getByEmailOrExternalId.getResult(UserService.java:834) ~[datahandler-13.4.0.jar:?]
        at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$getByEmailOrExternalId.getResult(UserService.java:814) ~[datahandler-13.4.0.jar:?]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [datahandler-13.4.0.jar:?]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [datahandler-13.4.0.jar:?]
        at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [datahandler-13.4.0.jar:?]
        at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-13.4.0.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by dineshr93** [comment]
i am using attachment id taken from this 
![image](https://user-images.githubusercontent.com/4498415/127520826-b8e275e0-a724-4bc8-adb2-c7ae49e6ab5e.png)

is this the right one?

**Comment by dineshr93** [comment]
my entire url to which i am sending delete request is below format

http://sw360_url.com:8080/resource/api/releases/b97686352d1d41b1bf7fc90d834e6166/attachments/**85c7fe3c92e947669482f5e2834e219f**

Id taken from the release resource of rest api  for the checker qual 2.5.2

**Comment by ravi110336** [comment]
Hi @dineshr93 , the url and id seems to be fine, the first step before calling the rest api endpoint the authorization fails as per the logs. Can you please check if the sw360 application works fine from the UI like different navigation to Project,Component etc.

**Comment by dineshr93** [comment]
Hi @ravi110336  Yes I am sure the pages was working fine(projects, releases etc.. ). Thats why I posted the error only on deletion api.

**Comment by dineshr93** [comment]
@ravi110336 

I successfull yupdated to d7d6f46 &  get the following error

```
{

  "timestamp": "2021-08-03T09:27:15.149716Z",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Could not delete attachments [85c7fe3c92e947669482f5e2834e219f] from release b97686352d1d41b1bf7fc90d834e6166"
}

```
**LOG**
```
2021-08-03 09:27:15 ERROR ProcessFunction:47 - Internal error processing getAttachmentUsages
com.cloudant.client.org.lightcouch.CouchDbException: 405 Method Not Allowed at http://localhost:5984/sw360db/_design/AttachmentUsage/_view/usagesByAttachment/queries. Error: method_not_allowed. Reason: Only GET,POST,HEAD allowed.
        at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:597) ~[cloudant-client-2.19.1.jar:?]
        at com.cloudant.client.api.CloudantClient.executeRequest(CloudantClient.java:411) ~[cloudant-client-2.19.1.jar:?]
        at com.cloudant.client.internal.views.ViewRequester.executeRequestWithResponseAsJson(ViewRequester.java:34) ~[cloudant-client-2.19.1.jar:?]
        at com.cloudant.client.internal.views.ViewMultipleRequester.performMultiRequest(ViewMultipleRequester.java:91) ~[cloudant-client-2.19.1.jar:?]
        at com.cloudant.client.internal.views.ViewMultipleRequester.getViewResponses(ViewMultipleRequester.java:54) ~[cloudant-client-2.19.1.jar:?]
        at org.eclipse.sw360.datahandler.cloudantclient.DatabaseRepositoryCloudantClient.multiRequestqueryView(DatabaseRepositoryCloudantClient.java:302) ~[datahandler-13.4.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.datahandler.db.AttachmentUsageRepository.getUsageForAttachments(AttachmentUsageRepository.java:125) ~[src-common-13.4.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.datahandler.db.AttachmentDatabaseHandler.getAttachmentUsages(AttachmentDatabaseHandler.java:227) ~[src-common-13.4.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.attachments.AttachmentHandler.getAttachmentsUsages(AttachmentHandler.java:185) ~[src-attachments-13.4.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.attachments.AttachmentHandler.getAttachmentUsages(AttachmentHandler.java:174) ~[src-attachments-13.4.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.datahandler.thrift.attachments.AttachmentService$Processor$getAttachmentUsages.getResult(AttachmentService.java:2253) ~[datahandler-13.4.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.datahandler.thrift.attachments.AttachmentService$Processor$getAttachmentUsages.getResult(AttachmentService.java:2233) ~[datahandler-13.4.0-SNAPSHOT.jar:?]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [datahandler-13.4.0-SNAPSHOT.jar:?]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [datahandler-13.4.0-SNAPSHOT.jar:?]
        at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [datahandler-13.4.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-13.4.0-SNAPSHOT.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-08-03 09:27:15 ERROR Sw360AttachmentService:149 - Could not check attachment usage for 85c7fe3c92e947669482f5e2834e219f
```
