### ISSUE TITLE
How to request for new clientId and client secret for sw360oauthclients

### ISSUE THREAD

**Issue by zhangjingcat** [eclipse-sw360/sw360#2012]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Hi Sw360,

I met problem with resetful api when trying to to get the oauth token. The username and password works well in the UI, so I think there might be something wrong with client id or client secret. 

```

Request:

curl --location --request POST 'https://our-sw360-server/authorization/oauth/token' \
--header 'Authorization: Basic xxxxxx' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=xxxxxx' \
--data-urlencode 'password=xxxxxx'


Response:

{
    "error": "unauthorized",
    "error_description": "No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken"
}

```

#### How to reproduce

I tried to re-deploy both sw360 and couchdb in k8s but the problem still exists.

### Versions

We are using the sw360 with version15.0.0-M1

#### SW360 logs

```
sw360-66cb7b7cb4-7hr5b 2023-06-21 06:09:33 ERROR TokenEndpoint:169 - Handling error: ProviderNotFoundException, No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
sw360-66cb7b7cb4-7hr5b org.springframework.security.authentication.ProviderNotFoundException: No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:232) ~[spring-security-core-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.authenticate(WebSecurityConfigurerAdapter.java:514) ~[spring-security-config-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.oauth2.provider.password.ResourceOwnerPasswordTokenGranter.getOAuth2Authentication(ResourceOwnerPasswordTokenGranter.java:71) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:72) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:67) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:583) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:132) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360-66cb7b7cb4-7hr5b  at jdk.internal.reflect.GeneratedMethodAccessor579.invoke(Unknown Source) ~[?:?]
sw360-66cb7b7cb4-7hr5b  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
sw360-66cb7b7cb4-7hr5b  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.eclipse.sw360.rest.authserver.security.customheaderauth.Sw360CustomHeaderAuthenticationFilter.doFilter(Sw360CustomHeaderAuthenticationFilter.java:146) [classes/:?]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.eclipse.sw360.rest.authserver.security.customheaderauth.Sw360CustomHeaderAuthenticationFilter.doFilter(Sw360CustomHeaderAuthenticationFilter.java:146) [classes/:?]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.eclipse.sw360.rest.common.Sw360CORSFilter.doFilter(Sw360CORSFilter.java:56) [rest-common-15.0.0.jar:?]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
sw360-66cb7b7cb4-7hr5b  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
sw360-66cb7b7cb4-7hr5b  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
sw360-66cb7b7cb4-7hr5b  at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by tuannn2** [comment]
hi @zhangjingcat , You can refer https://www.eclipse.org/sw360/docs/deployment/legacy/deploy-liferay7.3/  to get the plugin Private_Pages_7_3_3_GA4.lar and import that plugin

**Comment by zhangjingcat** [comment]
> hi @zhangjingcat , You can refer https://www.eclipse.org/sw360/docs/deployment/legacy/deploy-liferay7.3/ to get the plugin Private_Pages_7_3_3_GA4.lar and import that plugin

Hi @tuannn2 Thanks a lot and I configured that page pulugin now able to see the Admin - Oauth Client Page , but once I login with the super admin account "setup@sw360.org" and default password it seems I cannot pass the authorization sucessfully, is there any wrong action made from my side? 

<img width="1309" alt="Screenshot 2023-06-21 at 16 36 38" src="https://github.com/eclipse-sw360/sw360/assets/17232084/545ed283-3639-4937-b57a-599c64ae8f8a">

<img width="1258" alt="Screenshot 2023-06-21 at 16 38 40" src="https://github.com/eclipse-sw360/sw360/assets/17232084/5b67d3d2-0deb-42ba-8db5-eba372eb1c26">

<img width="1421" alt="Screenshot 2023-06-21 at 16 38 49" src="https://github.com/eclipse-sw360/sw360/assets/17232084/10154a24-d88b-4daa-86d3-603a43f6a3f9">

**Comment by tuannn2** [comment]
Hi @zhangjingcat , I think you should use user after you perform  **Import User Accounts for Testing step** in https://www.eclipse.org/sw360/docs/deployment/legacy/deploy-liferay7.3/

**Comment by tuannn2** [comment]
File import user: https://github.com/sw360/sw360vagrant/blob/master/shared/test_users_with_passwords_12345.csv

**Comment by heliocastro** [comment]
FIY, you curl request is missing a lot of things, like initial client_id/client_secret
Here's an example the correct way to do in bash shell:

```bash
#!/bin/bash

sw360_oauth_token_basic_credentials() {
    # This code uses JQ in order to parse the JSON response from the server.
    local user password credentials client_id client_secret response

    user="$1"
    password="$2"
    credentials=$(echo -n "$user:$password" | base64)

    response="$(
        curl -k -s -S \
            --user "${user}:${password}" \
            --header "Content-Type: application/json" \
            --header "Accept: application/json" \
            --header "Basic $credentials" \
            "${SW360_HOST}"/authorization/client-management
    )"
    client_id=$(jq -r '.[0].client_id' <<<"$response")
    client_secret=$(jq -r '.[0].client_secret' <<<"$response")
    credentials=$(echo -n "$client_id:$client_secret" | base64)

    response="$(
        curl -k -s -S \
            --user "${client_id}:${client_secret}" \
            --header "Content-Type: application/json" \
            --header "Accept: application/json" \
            --header "Basic $credentials" \
            "$SW360_HOST/authorization/oauth/token?grant_type=password&username=${user}&password=${password}"
    )"

    echo "This is your access token: $(jq -r '.access_token' <<<"$response")"
}
```

**Comment by zhangjingcat** [comment]
> FIY, you curl request is missing a lot of things, like initial client_id/client_secret Here's an example the correct way to do in bash shell:
> 
> ```shell
> #!/bin/bash
> 
> sw360_oauth_token_basic_credentials() {
>     # This code uses JQ in order to parse the JSON response from the server.
>     local user password credentials client_id client_secret response
> 
>     user="$1"
>     password="$2"
>     credentials=$(echo -n "$user:$password" | base64)
> 
>     response="$(
>         curl -k -s -S \
>             --user "${user}:${password}" \
>             --header "Content-Type: application/json" \
>             --header "Accept: application/json" \
>             --header "Basic $credentials" \
>             "${SW360_HOST}"/authorization/client-management
>     )"
>     client_id=$(jq -r '.[0].client_id' <<<"$response")
>     client_secret=$(jq -r '.[0].client_secret' <<<"$response")
>     credentials=$(echo -n "$client_id:$client_secret" | base64)
> 
>     response="$(
>         curl -k -s -S \
>             --user "${client_id}:${client_secret}" \
>             --header "Content-Type: application/json" \
>             --header "Accept: application/json" \
>             --header "Basic $credentials" \
>             "$SW360_HOST/authorization/oauth/token?grant_type=password&username=${user}&password=${password}"
>     )"
> 
>     echo "This is your access token: $(jq -r '.access_token' <<<"$response")"
> }
> ```

Hi @heliocastro , thanks a lot for your detailed examples, but it works well for our qa env and just fails for dev env, so I think it is still related with deployment issue with sw360 authorization server.  

The curl comes from this documents https://github.com/eclipse-sw360/sw360/blob/main/rest/resource-server/src/docs/asciidoc/api-guide.adoc

```
curl
-X POST
--user 'client-id:client-secret'
-d 'grant_type=password&username=<USERNAME>&password=<PASSWORD>' https://sw360.org/authorization/oauth/token -k
```

I will try to see whether something is wrong or missing in our dev deployment for sw360.

**Comment by zhangjingcat** [comment]
@heliocastro And I found this ticket https://github.com/eclipse-sw360/sw360/issues/1191 which is the same problem as me.

I have checked the /etc/sw360/sw360.properties file and see the  rest.apitoken.generator.enable = true and sw360.liferay.company.id = 20098 all configured successfully.

<img width="1000" alt="Screenshot 2023-06-23 at 09 17 25" src="https://github.com/eclipse-sw360/sw360/assets/17232084/5dc8b99e-2065-4499-803a-fda81e5d269f">


root@sw360-66cb7b7cb4-7hr5b:/etc/sw360# cat sw360.properties
# N.B this is the default build property file, defined in module build-configuration
backend.url= http://localhost:8080
release.externalkeys=NPM,Maven,PyPI,GitHub,RubyGems,NuGet,Bower,NIST,Golang,WhiteSourceID,HubComponentToken,Debian,Fedora,Ubuntu,CentOS,RedHat,KDE,Android,Packagist,openSUSE,OpenEmbedded,Alpine,Longtail,Anaconda,ClearLinux,APACHE_SOFTWARE,CocoaPods,Yocto,SourceForge,Conan,Crates,GNU,CPAN,Bitbucket,Dart,CRAN,GitLab,Launchpad,freedesktop,Hackage,CodePlex,Pear,Hex,SourceForgeJP,ALT_LINUX,OpenHub,CodeCenterComponentId
rest.apitoken.generator.enable = true
custom.welcome.page.guideline = true
sw360.liferay.company.id = 20098

**Comment by zhangjingcat** [comment]
Same issue found in sw360 official issue list:

https://github.com/eclipse-sw360/sw360/issues/1191

**Comment by zhangjingcat** [comment]
I can prove the clientId and clientSecret is fine as the erros is different for them

If clientId and clientSecret  is wrong:

<img width="1403" alt="Screenshot 2023-06-23 at 17 05 58" src="https://github.com/eclipse-sw360/sw360/assets/17232084/e392ab7e-8374-4816-a92b-39a1ac12b66c">


if username and password is wrong:

<img width="1422" alt="Screenshot 2023-06-23 at 17 06 18" src="https://github.com/eclipse-sw360/sw360/assets/17232084/8a1b43b3-8d8c-4957-9936-0d1a78bb7f57">

**Comment by tuannn2** [comment]
![API](https://github.com/eclipse-sw360/sw360/assets/94596393/445dd629-4058-4a5a-98ff-f5d96ff761f6)

Hi @zhangjingcat , You need to use both clientId, clientSecret and username pass word to get token.

**Comment by zhangjingcat** [comment]
> ![API](https://user-images.githubusercontent.com/94596393/248227612-445dd629-4058-4a5a-98ff-f5d96ff761f6.png)
> 
> Hi @zhangjingcat , You need to use both clientId, clientSecret and username pass word to get token.

Hi @tuannn2 thanks, actually it works for my qa env but not dev env, so the params I passed is clientId, clientSec which encodes as base64 in headers and username pass in the form data, this is not param issue, this is something related to deployment configuration, but when I got to see the pods in dev and qa ,  in /ect/sw360/authorization directory they looks really similar and I am still confused about what's wrong with them.

**Comment by zhangjingcat** [comment]
And I have proved my clientid and clientsecret to be correct as when I change username and password to a invalid account , it returns the same error as dev. So there might be something wrong in dev about validating the user account, even the setp@sw360.org with default password fails, that's relly weird
