### ISSUE TITLE
java.lang.RuntimeException: Current portal schema version 13.3.4 requires a newer version of Liferay (while rollback to 16)

### ISSUE THREAD

**Issue by dineshr93** [eclipse-sw360/sw360#2044]
### Description
Hello
I tried to upgrade from 16 to 17  as per the [doc ](https://eclipse.dev/sw360/docs/deployment/upgrading/upgrade_version_sw360_16_to_17/#ref3) [which has steps for liferay upgrade etc]

it threw the same error  https://github.com/eclipse-sw360/sw360/issues/1919 (raised by me previously)

So I tried to getback my old version sw360 16 (7b24df6) up and running with existing liferay-ce-portal-7.3.3-ga4 which ran perfectly previously, and while doing so I get the below mentioned error in the sw360 log.

Please how to resolve this error without liferay upgrade ? (so that i get back my running instance)

### Versions

* Last commit id on master:7b24df6 (16)
* Operating System (lsb_release -a):
* Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

#### SW360 logs

```

    __    ____________________  _____  __
   / /   /  _/ ____/ ____/ __ \/   \ \/ /
  / /    / // /_  / __/ / /_/ / /| |\  /
 / /____/ // __/ / /___/ _, _/ ___ |/ /
/_____/___/_/   /_____/_/ |_/_/  |_/_/

Starting Liferay Community Edition Portal 7.3.3 CE GA4 (Athanasius / Build 7303 / June 30, 2020)

2023-07-12 17:10:15.694 INFO  [main][StartupHelperUtil:103] There are no patches installed
Current portal schema version 13.3.4 requires a newer version of Liferay
2023-07-12 17:10:15.730 ERROR [main][MainServlet:299] java.lang.RuntimeException: Current portal schema version 13.3.4 requires a newer version of Liferay
java.lang.RuntimeException: Current portal schema version 13.3.4 requires a newer version of Liferay
        at com.liferay.portal.events.StartupHelperUtil.verifyRequiredSchemaVersion(StartupHelperUtil.java:221)
        at com.liferay.portal.events.StartupAction.doRun(StartupAction.java:112)
        at com.liferay.portal.events.StartupAction.run(StartupAction.java:60)
        at com.liferay.portal.internal.servlet.MainServlet.init(MainServlet.java:296)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4876)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5185)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1831)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
Stopping the server due to unexpected startup errors
```

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by hoangnt2** [comment]
@dineshr93 You can try running Liferay's migration script follow this guide https://eclipse.dev/sw360/docs/deployment/upgrading/upgrade_version_sw360_16_to_17/#liferay-database-migration. I am not sure it work for downgrade Liferay version but it will solve issue #1919

**Comment by dineshr93** [comment]
@hoangnt2 Thanks , I tried to upgrade from my old liferay 7.3.3-ga4
```
user@testserver:/opt/liferay-ce-portal-7.3.3-ga4/tools/portal-tools-db-upgrade-client$ ./db_upgrade.sh -j "-Xmx8000m -Dfile.encoding=UTF-8 -Duser.timezone=GMT"
JVM arguments: -Xmx8000m -Dfile.encoding=UTF-8 -Duser.timezone=GMT -Dexternal-properties=portal-upgrade.properties -Dserver.detector.server.id=tomcat
Loading jar:file:/opt/liferay-ce-portal-7.3.3-ga4/tomcat-9.0.33/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.liferay.petra.reflect.ReflectionUtil (file:/opt/liferay-ce-portal-7.3.3-ga4/tomcat-9.0.33/lib/ext/com.liferay.petra.reflect.jar) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of com.liferay.petra.reflect.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Loading jar:file:/opt/liferay-ce-portal-7.3.3-ga4/tomcat-9.0.33/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/portal.properties
Loading jar:file:/opt/liferay-ce-portal-7.3.3-ga4/tools/portal-tools-db-upgrade-client/com.liferay.portal.tools.db.upgrade.client.jar!/portal-upgrade.properties
Loading file:/opt/liferay-ce-portal-7.3.3-ga4/tools/portal-tools-db-upgrade-client/portal-upgrade-ext.properties
Loading file:/opt/liferay-ce-portal-7.3.3-ga4/tools/portal-tools-db-upgrade-client/portal-upgrade-database.properties
2023-07-19 08:48:01.940 INFO  [main][DialectDetector:159] Using dialect org.hibernate.dialect.PostgreSQLDialect for PostgreSQL 10.15
2023-07-19 08:48:03.484 INFO  [main][ModuleFrameworkImpl:1585] Starting initial bundles
2023-07-19 08:48:04.323 INFO  [main][ModuleFrameworkImpl:1871] Started initial bundles
2023-07-19 08:48:04.325 INFO  [main][ModuleFrameworkImpl:1924] Starting dynamic bundles
2023-07-19 08:48:09.064 INFO  [main][ModuleFrameworkImpl:1946] Started dynamic bundles
2023-07-19 08:48:09.065 INFO  [main][ModuleFrameworkImpl:1953] Starting web bundles
2023-07-19 08:48:10.245 INFO  [main][ModuleFrameworkImpl:2007] Started web bundles
2023-07-19 08:48:10.246 INFO  [main][ModuleFrameworkImpl:407] Navigate to Control Panel > Configuration > Gogo Shell and enter "lb" to see all bundles
2023-07-19 08:48:13.153 INFO  [main][StartupHelperUtil:103] There are no patches installed
java.lang.IllegalStateException: Attempting to deploy an older Liferay Portal version. Current build number is 7403 and attempting to deploy number 7303.
        at com.liferay.portal.tools.DBUpgrader.checkRequiredBuildNumber(DBUpgrader.java:105)
        at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:173)
        at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:130)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54)
```

may be ill try deploying **sw360 16**  to **liferay 7.4.3.18-ga18**

**Comment by hoangnt2** [comment]
@dineshr93, You can follow document https://eclipse.dev/sw360/docs/deployment/upgrading/upgrade_version_sw360_16_to_17. There some new steps for upgrading.

**Comment by dineshr93** [comment]
@hoangnt2  
I am using **Ubuntu 18.04.5 LTS**. is this recommended version

**Comment by dineshr93** [comment]
update @hoangnt2  The UI worked finally

however I see this error message at the log

![image](https://github.com/eclipse-sw360/sw360/assets/4498415/fb396af6-7f1b-43fc-b27f-b5f120e18bde)

**Comment by hoangnt2** [comment]
> 
> however I see this error message at the log
> 
> ![image](https://user-images.githubusercontent.com/4498415/254622863-fb396af6-7f1b-43fc-b27f-b5f120e18bde.png)

@dineshr93 You don't need to care that error, everything work normally.

> It kind of worked but UI looked very small and theme seems to be missing
Could you give me your screenshot? 
Maybe compile and re-deploy application will solve your problem.

**Comment by dineshr93** [comment]
> > however I see this error message at the log
> > ![image](https://user-images.githubusercontent.com/4498415/254622863-fb396af6-7f1b-43fc-b27f-b5f120e18bde.png)
> 
> @dineshr93 You don't need to care that error, everything work normally.
> 
> > It kind of worked but UI looked very small and theme seems to be missing
> 
> Could you give me your screenshot? Maybe compile and re-deploy application will solve your problem.

Hi @hoangnt2  I already did update and server is used by team. I am not installing in my PC . Next week Ill try to provide you the screen shot after performing the update mentioned here https://github.com/eclipse-sw360/sw360/pull/1811
