### ISSUE TITLE
Can't log in LDAP user

### ISSUE THREAD

**Issue by yyosioka** [eclipse-sw360/sw360#2348]
### Description

Can't log in LDAP user
Please let me know if there is anything that needs to be corrected.

#### How to reproduce

We have LDAP support in sw360-16.0.0-M1 and were able to log in using our Email address without any problems.　However, even with the exact same settings in sw360-18.0.2-M1, we are unable to get an email address and login fails.

### Versions
sw360-18.0.2-M1(https://github.com/eclipse-sw360/sw360/commit/ee9d2d0f272a30081f6aba3235f1dbd4a5706fa8)
docker environment

### Logs
2024-03-07 04:52:21 ERROR SW360Assert:141 - Invalid empty input!
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
	at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:128) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:84) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:79) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.projects.ProjectHandler.getMyProjects(ProjectHandler.java:100) ~[src-projects-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$getMyProjects.getResult(ProjectService.java:5096) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$getMyProjects.getResult(ProjectService.java:5073) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.apache.thrift.server.TServlet.doPost(TServlet.java:80) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) ~[src-common-18.0.0-SNAPSHOT.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[servlet-api.jar:4.0.FR]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:9.0.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[catalina.jar:9.0.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:9.0.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[catalina.jar:9.0.56]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.56]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.56]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2024-03-07 04:52:21 ERROR ProcessFunction:49 - Internal error processing getMyProjects
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
	at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:142) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:129) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:84) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:79) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.projects.ProjectHandler.getMyProjects(ProjectHandler.java:100) ~[src-projects-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$getMyProjects.getResult(ProjectService.java:5096) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$getMyProjects.getResult(ProjectService.java:5073) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.apache.thrift.server.TServlet.doPost(TServlet.java:80) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) ~[src-common-18.0.0-SNAPSHOT.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[servlet-api.jar:4.0.FR]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:9.0.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[catalina.jar:9.0.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:9.0.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[catalina.jar:9.0.56]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.56]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.56]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
04:52:21,104 ERROR [UserCacheHolder:76] Unable to fetch user...
java.util.concurrent.ExecutionException: org.apache.thrift.TApplicationException: getByEmail failed: unknown result
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592) ~[bundleFile:?]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:551) ~[bundleFile:?]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:111) ~[bundleFile:?]
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:247) ~[bundleFile:?]
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2345) ~[bundleFile:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[bundleFile:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189) ~[bundleFile:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079) ~[bundleFile:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4011) ~[bundleFile:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4034) ~[bundleFile:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5010) ~[bundleFile:?]
	at org.eclipse.sw360.portal.users.UserCache.get(UserCache.java:58) ~[bundleFile:?]
	at org.eclipse.sw360.portal.users.UserCacheHolder.loadUserFromEmail(UserCacheHolder.java:74) ~[bundleFile:?]
	at org.eclipse.sw360.portal.users.UserCacheHolder.loadUserFromEmail(UserCacheHolder.java:82) ~[bundleFile:?]
	at org.eclipse.sw360.portal.users.UserCacheHolder.getCurrentUser(UserCacheHolder.java:54) ~[bundleFile:?]
	at org.eclipse.sw360.portal.users.UserCacheHolder.getUserFromRequest(UserCacheHolder.java:90) ~[bundleFile:?]
	at org.eclipse.sw360.portal.portlets.homepage.MyTaskAssignmentsPortlet.serveTaskList(MyTaskAssignmentsPortlet.java:63) ~[bundleFile:?]
	at org.eclipse.sw360.portal.portlets.homepage.MyTaskAssignmentsPortlet.serveResource(MyTaskAssignmentsPortlet.java:55) ~[bundleFile:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:146) ~[portal-impl.jar:?]
	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:88) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:140) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:78) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115) ~[portal-kernel.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:40) ~[?:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:566) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.invokeResource(InvokerPortletImpl.java:681) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.serveResource(InvokerPortletImpl.java:494) ~[portal-impl.jar:?]
	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.serveResource(MonitoringInvokerPortlet.java:292) ~[?:?]
	at com.liferay.portlet.internal.PortletContainerImpl._serveResource(PortletContainerImpl.java:1072) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletContainerImpl.lambda$serveResource$4(PortletContainerImpl.java:267) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:421) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletContainerImpl.serveResource(PortletContainerImpl.java:260) ~[portal-impl.jar:?]
	at com.liferay.portlet.SecurityPortletContainerWrapper.serveResource(SecurityPortletContainerWrapper.java:199) ~[portal-

**Comment by KoukiHama** [comment]
Did you do test for ldap connection on LIFE RAY s instance settings?

**Comment by yyosioka** [comment]
@KoukiHama  I have not tested it.
How to test connection on LIFE RAY s instance settings?

**Comment by KoukiHama** [comment]
https://help.liferay.com/hc/en-us/articles/360029031771-LDAP

you can get info form there.

> This is all you need to make a regular connection to an LDAP directory. The rest of the configuration, however, may need to be customized, as it represents “best guesses” as to correct defaults. The default attribute mappings usually provide enough data to synchronize back to the Liferay DXP database when a user attempts to log in. To test the connection to your LDAP server, click the Test LDAP Connection button.

**Comment by yyosioka** [comment]
@KoukiHama  I checked and there is no way to make a test connection, there is no place to display test connection. If I am wrong, please let me know.

**Comment by KoukiHama** [comment]
This one.,

![image](https://github.com/eclipse-sw360/sw360/assets/39894802/9f898e73-19d8-4679-bf19-fc172dc954d2)

![image](https://github.com/eclipse-sw360/sw360/assets/39894802/d90e30a7-3669-4312-b786-800ddf8027a1)


![image](https://github.com/eclipse-sw360/sw360/assets/39894802/24b86d81-48b3-481e-9e50-01dd49209334)

**Comment by yyosioka** [comment]
@KoukiHama 
Thank you for your response.
Select instance Setting > LDAP > servers
But I am unable to add servers.
Selecting "Add" doesn't work.

Therefore, I am unable to view the "Test LDAP connection".

**Comment by yyosioka** [comment]
@KoukiHama 
I can't add or view them in [instance Setting > LDAP > servers]. As per the following screen.
![ldap](https://github.com/eclipse-sw360/sw360/assets/62535924/f16cfe25-1578-46f9-869f-1c112d19174f)

**Comment by yyosioka** [comment]
@KoukiHama 

I have checked the logs.
I am able to connect to the LDAP server, but sw360-16.0.0-M1 and sw360-18.0.2 have different behavior when "Deparment" is not set.

In sw360-16.0.0, it was possible to save to "couchdb" even if "Deparment" was not set.
As of sw360-18.0.2, it is no longer possible to save to "couchdb" unless "Deparment" is set.

1 Is there any way to uncheck "Deparment" when saving to "couchdb"?
2 Is there any way to set a default value for "Deparment" to avoid this error?

**Log Analysis Results
An error occurs because there is no "Deparment" in the information obtained from LDAP.**
2024-03-08 06:55:44 ERROR SW360Assert:141 - User Department was empty in User(type:user, email:xxxxxx@xxxx.co.jp, userGroup:USER, externalid:xxxi, fullname:xx x, givenname:xx, lastname:x, department:)	
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:128) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:84) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.datahandler.common.SW360Assert.assertUser(SW360Assert.java:74) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.users.UserHandler.addUser(UserHandler.java:114) ~[src-users-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$addUser.getResult(UserService.java:2278) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$addUser.getResult(UserService.java:2255) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.apache.thrift.server.TServlet.doPost(TServlet.java:80) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) ~[src-common-18.0.0-SNAPSHOT.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[servlet-api.jar:4.0.FR]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.56]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:9.0.56]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[catalina.jar:9.0.56]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:9.0.56]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[catalina.jar:9.0.56]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-coyote.jar:9.0.56]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.56]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-coyote.jar:9.0.56]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) ~[tomcat-coyote.jar:9.0.56]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.56]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.56]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.56]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.56]
at java.lang.Thread.run(Thread.java:829) ~[?:?]

**Cannot save to couchdb because there is no "department".**
2024-03-08 06:55:44 ERROR ProcessFunction:49 - Internal error processing addUser
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:142) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:129) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:84) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.datahandler.common.SW360Assert.assertUser(SW360Assert.java:74) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.users.UserHandler.addUser(UserHandler.java:114) ~[src-users-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$addUser.getResult(UserService.java:2278) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.datahandler.thrift.users.UserService$Processor$addUser.getResult(UserService.java:2255) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.apache.thrift.server.TServlet.doPost(TServlet.java:80) ~[datahandler-18.0.0-SNAPSHOT.jar:?]
at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) ~[src-common-18.0.0-SNAPSHOT.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[servlet-api.jar:4.0.FR]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.56]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:9.0.56]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[catalina.jar:9.0.56]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[catalina.jar:9.0.56]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:9.0.56]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[catalina.jar:9.0.56]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-coyote.jar:9.0.56]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:9.0.56]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-coyote.jar:9.0.56]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) ~[tomcat-coyote.jar:9.0.56]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:9.0.56]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:9.0.56]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:9.0.56]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:9.0.56]
at java.lang.Thread.run(Thread.java:829) ~[?:?]

**Comment by yyosioka** [comment]
@KoukiHama 
Thank you for your answer.
Docker could also be configured on the "User and Organization" page of liferay.

Now that the problem is solved, I will close this case.
