### ISSUE TITLE
deprecated parameter and keycloak start error while using keycloak 26.0.5

### ISSUE THREAD

**Issue by dineshr93** [eclipse-sw360/sw360#2733]
### Description

[keycloak 26.0.5](https://github.com/eclipse-sw360/sw360/commit/f2b202b7a791e1cd00d84b3618e1e2332a8558c0) throws below error

when running 

[c4b75cf5/keycloak/README.md#L6](https://github.com/eclipse-sw360/sw360/blame/c4b75cf53197adf75a0c6ba35a680582420d69c5/keycloak/README.md#L67)

```
./kc.sh start --log="console,file" 
--hostname-strict-backchannel=false 
--http-enabled=true 
--http-port=8083 
--https-port=8533 
--hostname-strict=false 
--hostname-strict-https=false
```

```
Error details:
jakarta.persistence.PersistenceException: [PersistenceUnit: keycloak-default] Unable to build Hibernate SessionFactory
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:129)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:89)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:73)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:154)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Persistence unit 'keycloak-default' was configured to run with a database version of at least '12.0.0', but the actual version is '10.23.0'. Consider upgrading your database. Alternatively, rebuild your application with 'quarkus.datasource.db-version=10.23.0' (but this may disable some features and/or impact performance negatively).
        at io.quarkus.hibernate.orm.runtime.service.QuarkusRuntimeInitDialectFactory.checkActualDbVersion(QuarkusRuntimeInitDialectFactory.java:70)
        at io.quarkus.hibernate.orm.runtime.observers.QuarkusSessionFactoryObserverForDbVersionCheck.sessionFactoryCreated(QuarkusSessionFactoryObserverForDbVersionCheck.java:15)
        at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:323)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:87)
        ... 6 more
dira271641@denue6pr251:/opt/keycloak-26.0.5/bin$ bash kc.sh start --log="console,file" --hostname-backchannel-dynamic=false --http-enabled=true --http-port=8083 --https-port=8533 --hostname-strict=false --verbose
```

Also In `keycloak 26.0.5` 
[keycloak changes-25_0_0.adoc](https://github.com/keycloak/keycloak/blob/main/docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc)

parameter `--hostname-strict-backchannel` is replaced with `hostname-backchannel-dynamic`

parameter `--hostname-strict-https` is `deprecated`

**Comment by dineshr93** [comment]
closing this as this issue is moved to  https://github.com/eclipse-sw360/sw360-frontend/issues/355
